# Generated by Django 4.0.1 on 2022-03-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='mumber',
            new_name='number',
        ),
    ]
