# Generated by Django 3.2.13 on 2022-05-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211228_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesOrder',
        ),
    ]
